server:
  port: 9095
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

azure:
  vision:
    endpoint: <endpoint>
    key: <api-key>
aws:
  accessKey: <accesskey>
  secretKey: <secretkey>
  region: us-east-1

